add alt text for exhibit card images on home page
projectblacklight/spotlight pull request #2768
Opened 2021-06-22 14:24 UTC by elrayle

Fixes #2767

Implements second option setting the alt text to Exhibit + exhibit title (e.g. Exhibit Maps).

2021-06-22 14:28 UTC, cbeer requested changes
As I noted in https://github.com/projectblacklight/spotlight/issues/2767#issuecomment-866016690, I don't believe this is the expected behavior for decorative images.

2021-06-22 14:31 UTC, elrayle commented
@cbeer I saw your comment after I submitted the PR.  I am running this by our accessibility expert to see if he knows why Site Improve tagged this as an issue given your observations.

2021-06-25 15:43 UTC, elrayle commented
I moved the link outside the image and the title so there is only one link.  This allows the `role=presentation` attribute on the image to allow for an empty `alt` attribute.

2021-07-27 17:44 UTC, elrayle commented
@cbeer Can you take another look at this?  I believe that I addressed your comments and that this change is necessary to fix SiteImprove errors on the Home page.

![image](https://user-images.githubusercontent.com/6855473/127202303-5aece277-914d-4668-a2eb-28b1df0d8576.png)

2021-08-06 14:01 UTC, elrayle commented
The latest version of SiteImprove no longer sees this as an error.  For more information, see the [comment in Issue #2767](https://github.com/projectblacklight/spotlight/issues/2767#issuecomment-894280608). 
 
Closing.

2021-08-06 14:01 UTC, closed without merging