Replacing header nav partial with header component
projectblacklight/spotlight pull request #3136
Opened 2024-09-19 20:42 UTC by hudajkhan

**Context**
Relates to having tests pass with Blacklight 8.3 and using a Spotlight HeaderComponent instead of shared/_header_navbar.  The Spotlight header is almost exactly the same as the default Blacklight header except it does not include the search bar (which is elsewhere on the page). 
Refer to https://github.com/projectblacklight/spotlight/issues/3047 and this comment which includes a checklist of tests to fix: https://github.com/projectblacklight/spotlight/issues/3047#issuecomment-2359456286

For 8.3, the following tests are failing:
 - rspec ./spec/views/shared/_header_navbar.html.erb_spec.rb:8 # shared/_header_navbar has nav links
 - rspec ./spec/views/spotlight/pages/show.html.erb_spec.rb:46 # spotlight/pages/show when rendering with layout does not double-escape HTML entities in the HTML title
 - rspec ./spec/views/spotlight/pages/show.html.erb_spec.rb:50 # spotlight/pages/show when rendering with layout includes analytics reporting

**What this pull request does**
- Removes the header_navbar partial.
- Creates a Spotlight HeaderComponent whose partial displays on the top bar. 
- Adds the Spotlight Header Component to the configuration as the header component.
- Adds blacklight configuration information for the show html rspec to pass. 

**How to test**
These tests should still pass in Blacklight 7.

How to test with Blacklight 8: Generate test app (.internal_test_app). Update the internal test app's Gemfile to use Blacklight 8.3. Run bundle install for the internal test app. Then run rspec ./spec/views/spotlight/pages/show.html.erb_spec.rb:46 and rspec ./spec/views/spotlight/pages/show.html.erb_spec.rb:50.

2024-09-20 21:26 UTC, cbeer commented
I wonder if there's a backwards-compatible way to introduce this change (that won't require downstream applications to add the `header_component` configuration).

Maybe we could keep the header_navbar partial?

```
<% if blacklight_config.header_component.present? && blacklight_config.header_component != Blacklight::HeaderComponent %>
<%= render blacklight_config.header_component.new(blacklight_config: blacklight_config) %>
<% else %>
<%# TODO: deprecation warning to encourage downstream to add the config? %>
<%= render Spotlight::HeaderComponent.new(blacklight_config: blacklight_config) %>
<% end %>
```

2024-09-20 23:54 UTC, hudajkhan commented
@cbeer I brought the partial back and its associated test and set up with a deprecation warning.

2024-09-21 14:05 UTC, jcoyne requested changes

2024-09-21 14:05 UTC, jcoyne commented on spec/views/shared/_header_navbar.html.erb_spec.rb
> +describe 'shared/_header_navbar', type: :view do
```suggestion
RSpec.describe 'shared/_header_navbar', type: :view do
```

2024-09-21 14:05 UTC, jcoyne commented on spec/views/shared/_header_navbar.html.erb_spec.rb
> +    expect(rendered).to have_selector '#user-util-collapse', text: 'links'
Do we need to have a view test at all?  View tests are deprecated in rails.  Instead can you use a request test, feature test, or a component test?

2024-09-21 14:05 UTC, jcoyne commented on app/views/shared/_header_navbar.html.erb
> +  <% ActiveSupport::Deprecation.warn("_header_navbar.html.erb will be deprecated in future versions. Please use Blaclight configuration to specify your HeaderComponent.") %>
```suggestion
  <% ActiveSupport::Deprecation.warn("_header_navbar.html.erb will be deprecated in future versions. Please use Blacklight configuration to specify your HeaderComponent.") %> 
```

2024-09-23 18:38 UTC, hudajkhan commented
@jcoyne I addressed your suggestions.  Rubocop said removing the "freeze" line at the beginning of the file was wrong (for the feature test version)

2024-09-23 19:00 UTC, jcoyne commented
@hudajkhan needs a rebase

2024-09-23 20:33 UTC, cbeer commented on app/views/shared/_header_navbar.html.erb
> +  <% ActiveSupport::Deprecation.new('5.0', 'Spotlight').warn("_header_navbar.html.erb will be deprecated in future versions. Please use Blacklight configuration to specify your HeaderComponent.") %>
```suggestion
  <% Spotlight.deprecator.warn("_header_navbar.html.erb will be deprecated in future versions. Please use Blacklight configuration to specify your HeaderComponent.") %>
```

2024-09-23 20:37 UTC, hudajkhan commented on app/views/shared/_header_navbar.html.erb
> +  <% ActiveSupport::Deprecation.new('5.0', 'Spotlight').warn("_header_navbar.html.erb will be deprecated in future versions. Please use Blacklight configuration to specify your HeaderComponent.") %>
Changes, thanks

2024-09-23 22:29 UTC, jcoyne approved these changes

2024-09-23 22:30 UTC, merged