remove breadcrumb library
projectblacklight/spotlight pull request #3166
Opened 2024-10-01 22:04 UTC by dnoneill

2024-10-02 19:17 UTC, dnoneill commented on app/views/shared/_breadcrumbs.html.erb
> +<% if defined?(breadcrumbs) && breadcrumbs.present? %>
This got added because spec/features/confirm_email_spec.rb:8 keeps failing without it.

2024-10-03 13:01 UTC, hackartisan commented
Can this PR please reference an issue with information about what / why?

2024-10-03 15:09 UTC, dnoneill commented
@hackartisan Linked.

2024-10-04 18:26 UTC, dnoneill commented on app/views/shared/_breadcrumbs.html.erb
> +<% if defined?(breadcrumbs) && breadcrumbs.present? %>
Following this ```

I think if you define these in Spotlight::Controller instead and add breadcrumbs to the list of helpers in the included do block also in Spotlight::Controller you could remove the separate helper_method :breadcrumbs entries in CatalogController and ApplicationController.
```

Fixed the problem. I already had a component already made so I just added it anyway.

2024-10-04 19:43 UTC, corylown requested changes

2024-10-04 19:43 UTC, corylown commented on app/components/breadcrumbs_component.rb
> +class BreadcrumbsComponent < ViewComponent::Base
This and its template should probably go in `app/components/spotlight` and be wrapped in `module Spotlight` like all the other spotlight components.

2024-10-04 19:43 UTC, corylown commented on app/controllers/spotlight/catalog_controller.rb
> +
I don't think you need this anymore now that `helper_method :breadcrumbs` is set in `Spotlight::Controller`
```suggestion
```

2024-10-04 19:43 UTC, corylown commented on app/controllers/concerns/spotlight/controller.rb
> +      helper_method :breadcrumbs
```suggestion
      helper_method :breadcrumbs, :current_site, :current_exhibit, :current_masthead, :exhibit_masthead?, :resource_masthead?
      before_action :set_exhibit_locale_scope, :set_locale
```

2024-10-04 19:43 UTC, corylown commented on app/components/breadcrumbs_component.rb
> +class BreadcrumbsComponent < ViewComponent::Base
Add a test for the component?

2024-10-04 21:52 UTC, corylown approved these changes

2024-10-04 21:52 UTC, merged