add controlled vocab functionality for tag_list
projectblacklight/spotlight pull request #3169
Opened 2024-10-04 15:36 UTC by dnoneill

closes https://github.com/sul-dlss/exhibits/issues/2492

2024-10-04 16:56 UTC, dnoneill commented on app/components/tag_list_form_component.html.erb
> +    <div class="overflow-scroll rounded border px-3 py-2 h-25" style="overflow: scroll; height: 25vh!important;">
This inline style can get removed as soon as we update to bootstrap 5. I can move this to a css file but it didn't seem to make sense due to the upgrade we are doing soon.

2024-10-04 21:40 UTC, corylown requested changes

2024-10-04 21:40 UTC, corylown commented on app/components/tag_list_form_component.rb
> +class TagListFormComponent < ViewComponent::Base
component should be namespaced in `module Spotlight` and moved to `app/components/spotlight`

2024-10-07 19:14 UTC, corylown approved these changes

2024-10-07 19:14 UTC, merged